SELECT B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(BS.SALES*B.PRICE) AS TOTAL_SALES
FROM BOOK B
JOIN AUTHOR A ON B.AUTHOR_ID= A.AUTHOR_ID
JOIN (
    SELECT BOOK_ID, SUM(SALES) AS SALES
    FROM BOOK_SALES 
    WHERE DATE_FORMAT(SALES_DATE,"%Y-%m")='2022-01'
    GROUP BY BOOK_ID
) BS
ON B.BOOK_ID=BS.BOOK_ID
GROUP BY B.AUTHOR_ID, B.CATEGORY

ORDER BY B.AUTHOR_ID ASC, B.CATEGORY DESC;