WITH A AS (
    SELECT
        C.CAR_ID,
        C.CAR_TYPE,
        C.DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR C
    WHERE C.CAR_TYPE IN ('세단', 'SUV')
      AND NOT EXISTS (
          SELECT 1
          FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
          WHERE H.CAR_ID = C.CAR_ID
            AND H.START_DATE <= '2022-11-30'
            AND H.END_DATE   >= '2022-11-01'
          
      )
),
B AS (
    SELECT
        A.CAR_ID,
        A.CAR_TYPE,
        FLOOR(A.DAILY_FEE * 30 * (100 - P.DISCOUNT_RATE) / 100.0) AS FEE
    FROM A
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
      ON P.CAR_TYPE = A.CAR_TYPE
     AND P.DURATION_TYPE = '30일 이상'
)
SELECT
    CAR_ID,
    CAR_TYPE,
    FEE
FROM B
WHERE FEE >= 500000
  AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;