-- 코드를 입력하세요
SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, UI.GENDER,COUNT(DISTINCT OS.USER_ID) AS USERS
FROM ONLINE_SALE OS
JOIN USER_INFO UI ON OS.USER_ID= UI.USER_ID
WHERE UI.GENDER IS NOT NULL

GROUP BY YEAR(SALES_DATE),MONTH(SALES_DATE), UI.GENDER
ORDER BY YEAR(SALES_DATE) ASC,MONTH(SALES_DATE) ASC,GENDER ASC
