-- 코드를 입력하세요
SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM (
    SELECT 
    CATEGORY, PRICE, PRODUCT_NAME,
    ROW_NUMBER() OVER(
        PARTITION BY CATEGORY
        ORDER BY PRICE DESC
    ) RM
    FROM FOOD_PRODUCT
) t
WHERE CATEGORY IN ('식용유','과자', '국','김치')
AND RM=1

ORDER BY MAX_PRICE DESC;